API/API.csproj
API/Contracts/IGeneralRepository.cs
API/Repositories/GeneralRepository.cs

feat: create general repository and interface

---

API/Contracts/IAccountRepository.cs
API/Repositories/AccountRepository.cs

Create Account Repository and Interface

---

API/Contracts/IAccountRoleRepository.cs
API/Repositories/AccountRoleRepository.cs

feat: create account role repository and interface

---

API/Contracts/IRoleRepository.cs
API/Repositories/RoleRepository.cs

feat: create role repository and interface

---

API/Contracts/IEmployeeRepository.cs
API/Repositories/EmployeeRepository.cs

feat: create employee repository and interface

---

API/Contracts/IHistoryRepository.cs
API/Repositories/HistoryRepository.cs

feat: create history repository and interface

---

API/Contracts/IOvertimeRepository.cs
API/Repositories/OvertimeRepository.cs

feat: create overtime repository and interface

---

API/Contracts/IPayslipRepository.cs
API/Repositories/PayslipRepository.cs

feat: create payslip repository and interface

---

API/Data/OvertimeDbContext.cs
API/Migrations/20230724015801_InitialDatabase.Designer.cs
API/Migrations/20230724015801_InitialDatabase.cs
API/Migrations/OvertimeDbContextModelSnapshot.cs
API/Models/Employee.cs
API/Models/History.cs
API/Models/Overtime.cs
API/Models/Payslip.cs

feat: update database and modals

---

API/DTOs/Employees/NewEmployeesDto.cs

feat: create employee dto

---

API/Contracts/IEmployeeRepository.cs

feat: update employee interface

---

API/DTOs/Overtimes/GetOvertimeDTO.cs
API/DTOs/Overtimes/NewOvertimeDTO.cs
ClientOvertime/ClientOvertime.csproj

feat : create overtime dto

---

API/DTOs/Overtimes/GetOvertimeDTO.cs

feat : adding property overtime dto

---

API/DTOs/Accounts/NewAccountDto.cs
API/DTOs/Employees/NewEmployeeDto.cs

feat: create account dto

---

API/Data/OvertimeDbContext.cs
API/Migrations/20230724063925_InitialDatabase.Designer.cs
API/Migrations/20230724063925_InitialDatabase.cs
API/Migrations/OvertimeDbContextModelSnapshot.cs
API/Models/Employee.cs

feat: update database manager

---

API/DTOs/Overtimes/GetOvertimeDTO.cs
API/DTOs/Overtimes/NewOvertimeDTO.cs
API/DTOs/Overtimes/UpdateOvertimeDto.cs

feat : adding entity overtime dto

---

API/DTOs/Payslips/GetPayslipDto.cs
API/DTOs/Payslips/NewPayslipDto.cs
API/DTOs/Payslips/UpdatePayslip.cs

feat : adding entity payslip

---

API/DTOs/Accounts/GetAccountDto.cs
API/DTOs/Accounts/NewAccountDto.cs
API/DTOs/Accounts/UpdateAccountDto.cs
API/Models/Employee.cs
API/Models/History.cs
API/Models/Payslip.cs

feat: update account dto

---

API/DTOs/Histories/GetHistoryDto.cs
API/DTOs/Histories/NewHistoryDto.cs
API/DTOs/Histories/UpdateHistoryDto.cs

feat: create hostory dto

---

API/DTOs/AccountRoles/GetAccountRoleDto.cs
API/DTOs/AccountRoles/NewAccountRoleDto.cs
API/DTOs/AccountRoles/UpdateAccountRoleDto.cs

feat: create account role dto

---

API/Services/EmployeeService.cs

feat: create service employee

---

API/DTOs/Employees/UpdateEmployeeDto.cs
API/Migrations/20230724104425_InitialDatabase.Designer.cs
API/Migrations/20230724104425_InitialDatabase.cs
API/Migrations/OvertimeDbContextModelSnapshot.cs
API/Models/Employee.cs

feat: refactor-database

---

API/Contracts/IEmployeeRepository.cs
API/Repositories/EmployeeRepository.cs
API/Services/EmployeeService.cs
API/Utilities/Handlers/GenerateHandler.cs

feat: create employee service

---

API/API.csproj
API/Controllers/EmployeeController.cs
API/DTOs/Employees/GetEmployeeDto.cs
API/Program.cs
API/Utilities/Handlers/ResponseHandler.cs

feat: refactor employee repository and service

---

API/Services/OvertimeService.cs

feat : adding overtime service

---

API/Controllers/RoleController.cs
API/DTOs/Roles/GetRoleDto.cs
API/Program.cs
API/Services/RoleService.cs

feat: adding role controller and service

---

API/Services/AccountService.cs

feat: create account service

---

API/Controllers/AccountController.cs
API/DTOs/AccountRoles/GetAccountRoleDto.cs
API/DTOs/AccountRoles/NewAccountRoleDto.cs
API/DTOs/AccountRoles/UpdateAccountRoleDto.cs
API/DTOs/Accounts/NewAccountDto.cs
API/Program.cs
API/Services/AccountService.cs

feat: create account controller

---

API/Program.cs
API/Services/AccountRoleService.cs

feat: create account role service

---

API/DTOs/Overtimes/UpdateOvertimeDto.cs
API/Program.cs
API/Services/PayslipService.cs

feat: creating payslip service

---

API/Controllers/PayslipController.cs

feat : adding controller payslip

---

API/Controllers/AccountRoleController.cs

feat: create account role controller

---

API/Controllers/HistoryController.cs
API/DTOs/AccountRoles/NewAccountRoleDto.cs
API/DTOs/Histories/GetHistoryDto.cs
API/Program.cs
API/Services/HistoryService.cs

feat: adding history controller and history

---

API/API.csproj
API/Contracts/IAccountRepository.cs
API/Contracts/IAccountRoleRepository.cs
API/Contracts/IEmployeeRepository.cs
API/Contracts/IRoleRepository.cs
API/Contracts/ITokenHandler.cs
API/Controllers/AccountController.cs
API/DTOs/Accounts/LoginDto.cs
API/DTOs/Accounts/RegisterDto.cs
API/Program.cs
API/Repositories/AccountRepository.cs
API/Repositories/AccountRoleRepository.cs
API/Repositories/EmployeeRepository.cs
API/Repositories/RoleRepository.cs
API/Services/AccountService.cs
API/Utilities/Handlers/HashingHandler.cs
API/Utilities/Handlers/TokenHandler.cs
API/Utilities/Validations/RegisterValidation.cs
ClientOvertime/ClientOvertime.csproj

feat: adding register and login jwt

---

API/Utilities/Validations/RegisterValidation.cs

feat : refactor register validatio

---

API/Utilities/Validations/LoginValidator.cs

feat : adding login validator

---

API/Controllers/EmployeeController.cs
API/DTOs/Employees/GetAllEmployeeDto.cs
API/Services/EmployeeService.cs

feat : adding end point get all employee

---

API/Services/AccountService.cs

feat: refactor register account

---

API/Contracts/IEmailHandler.cs
API/Contracts/IGeneralRepository.cs
API/Controllers/AccountRoleController.cs
API/DTOs/Accounts/ForgotPasswordDto.cs
API/Program.cs
API/Services/AccountService.cs
API/Utilities/Handlers/EmailHandler.cs
API/Utilities/Validations/ForgotPasswordValidation.cs

feat: create validation forgot password

---

API/Contracts/IEmailHandler.cs
API/Contracts/IEmployeeRepository.cs
API/Controllers/AccountController.cs
API/Controllers/EmployeeController.cs
API/Controllers/HistoryController.cs
API/DTOs/Accounts/ForgotPasswordDto.cs
API/DTOs/Accounts/GetAccountDto.cs
API/DTOs/Accounts/UpdateAccountDto.cs
API/DTOs/Employees/GetManagerDto.cs
API/DTOs/Histories/GetAllHistoryDto.cs
API/DTOs/Overtimes/GetOvertimeDTO.cs
API/DTOs/Overtimes/NewOvertimeDTO.cs
API/DTOs/Overtimes/UpdateOvertimeDto.cs
API/DTOs/Payslips/NewPayslipDto.cs
API/Data/OvertimeDbContext.cs
API/Migrations/20230725162749_UpdateDatabase.Designer.cs
API/Migrations/20230725162749_UpdateDatabase.cs
API/Models/Account.cs
API/Models/Overtime.cs
API/Program.cs
API/Repositories/EmployeeRepository.cs
API/Services/AccountService.cs
API/Services/EmployeeService.cs
API/Services/HistoryService.cs
API/Utilities/Handlers/EmailHandler.cs
API/Utilities/Handlers/GenerateHandler.cs

feat: uppdate database and create validasi forget password

---

API/Services/AccountService.cs

feat: refactor hashPassword

---

ClientOvertime/Views/Home/Index.cshtml

feat: edit login landing page

---

API/API.csproj
ClientOvertime/ClientOvertime.csproj
ClientOvertime/Contracts/IAccountRepository.cs
ClientOvertime/Controllers/AccountController.cs
ClientOvertime/Program.cs
ClientOvertime/Repositories/AccountRepository.cs
ClientOvertime/ViewModels/Accounts/AccountVMLogin.cs
ClientOvertime/Views/Account/Index.cshtml
ClientOvertime/Views/Account/Login.cshtml
ClientOvertime/Views/Shared/_LayoutDashboard.cshtml
ClientOvertime/Views/Shared/_LayoutLogin.cshtml
ClientOvertime/appsettings.json
ClientOvertime/wwwroot/Purple/assets/css/style.css

feat: add login dashboard

---

ClientOvertime/Contracts/IAccountRepository.cs
ClientOvertime/Controllers/AccountController.cs
ClientOvertime/Controllers/DashboardController.cs
ClientOvertime/Program.cs
ClientOvertime/Repositories/AccountRepository.cs
ClientOvertime/Repositories/GeneralRepository.cs
ClientOvertime/ViewModels/Accounts/AccountVMLogin.cs
ClientOvertime/Views/Account/Login.cshtml
ClientOvertime/Views/Employee/Create.cshtml
ClientOvertime/Views/Home/Index.cshtml
ClientOvertime/Views/Shared/_LayoutDashboard.cshtml
ClientOvertime/Views/Shared/_LayoutLogin.cshtml
ClientOvertime/appsettings.json

feat : fix login

---

API/Contracts/IOvertimeRepository.cs
API/Controllers/OvertimeController.cs
API/DTOs/Overtimes/OvertimeCreateDummyDto.cs
API/DTOs/Overtimes/OvertimeRemainingDto.cs
API/Migrations/20230731080836_Update-Migration.Designer.cs
API/Migrations/20230731080836_Update-Migration.cs
API/Models/Overtime.cs
API/Repositories/OvertimeRepository.cs
API/Services/OvertimeService.cs

feat: create ovetime remaining

---

API/Contracts/IOvertimeRepository.cs
API/Controllers/OvertimeController.cs
API/DTOs/Overtimes/OvertimeRemainingDto.cs
API/Repositories/OvertimeRepository.cs
API/Services/AccountService.cs
API/Services/OvertimeService.cs
ClientOvertime/Contracts/IOvertimeRepository.cs
ClientOvertime/Controllers/OvertimeController.cs
ClientOvertime/Repositories/OvertimeRepository.cs
ClientOvertime/ViewModels/Overtimes/OvertimeVMRequest.cs
ClientOvertime/Views/Overtime/Index.cshtml
ClientOvertime/Views/Shared/_LayoutDashboard.cshtml

feat: adding Employee Overtime

---

ClientOvertime/Contracts/IAccountRepository.cs
ClientOvertime/Controllers/AccountController.cs
ClientOvertime/Program.cs
ClientOvertime/Repositories/AccountRepository.cs
ClientOvertime/ViewModels/Accounts/AccountVMChangePassword.cs
ClientOvertime/ViewModels/Accounts/AccountVMForgotPassword.cs
ClientOvertime/Views/Account/ChangePassword.cshtml
ClientOvertime/Views/Account/ForgotPassword.cshtml
ClientOvertime/appsettings.json

feat: add forgot password client

---

API/DTOs/Overtimes/OvertimeRemainingDto.cs
API/Repositories/OvertimeRepository.cs
API/Services/OvertimeService.cs
ClientOvertime/Controllers/OvertimeController.cs
ClientOvertime/ViewModels/Overtimes/OvertimeVMRequest.cs
ClientOvertime/Views/Overtime/Create.cshtml
ClientOvertime/Views/Overtime/Index.cshtml

feat: update history by user

---

API/Contracts/IOvertimeRepository.cs
API/Controllers/OvertimeController.cs
API/Repositories/OvertimeRepository.cs
API/Services/OvertimeService.cs

feat: adding overtime by manager Guid

---

API/DTOs/Payslips/PayslipDtoCreate.cs
API/DTOs/Payslips/PayslipDtoGet.cs
API/Migrations/20230802164258_UpdatePayslip.Designer.cs
API/Migrations/20230802164258_UpdatePayslip.cs
API/Models/Payslip.cs

feat: update database payslip

---

API/Controllers/OvertimeController.cs
ClientOvertime/Contracts/IOvertimeRepository.cs
ClientOvertime/Controllers/OvertimeController.cs
ClientOvertime/Repositories/OvertimeRepository.cs
ClientOvertime/Views/Overtime/GetByManager.cshtml
ClientOvertime/Views/Shared/_LayoutDashboard.cshtml

feat: adding overtime manager in client

---

API/Controllers/OvertimeController.cs
API/Services/OvertimeService.cs
ClientOvertime/Contracts/IOvertimeRepository.cs
ClientOvertime/Controllers/AccountController.cs
ClientOvertime/Controllers/EmployeeController.cs
ClientOvertime/Controllers/OvertimeController.cs
ClientOvertime/Controllers/PayslipController.cs
ClientOvertime/ViewModels/Overtimes/OvertimeVMRequest.cs
ClientOvertime/Views/Home/401.cshtml
ClientOvertime/Views/Home/403.cshtml
ClientOvertime/Views/Home/404.cshtml
ClientOvertime/Views/Overtime/Detail.cshtml
ClientOvertime/Views/Overtime/Index.cshtml
ClientOvertime/Views/Payslip/Index.cshtml
ClientOvertime/Views/Shared/_LayoutDashboard.cshtml

feat: add authorize page

---

API/Controllers/OvertimeController.cs
API/DTOs/Overtimes/OvertimeCreateDummyDto.cs
API/DTOs/Overtimes/OvertimeDtoCreate.cs
API/DTOs/Overtimes/OvertimeUpdateStatus.cs
API/Repositories/OvertimeRepository.cs
API/Services/OvertimeService.cs

feat: adding update features status

---

API/Controllers/OvertimeController.cs
API/DTOs/Overtimes/OvertimeDtoGet.cs
API/Services/OvertimeService.cs
API/Utilities/Handlers/TokenHandler.cs
ClientOvertime/Views/Overtime/Index.cshtml

feat: upadate detail overtime

---

ClientOvertime/Views/Account/ChangePassword.cshtml
ClientOvertime/Views/Account/ForgotPassword.cshtml
ClientOvertime/Views/Account/Login.cshtml
ClientOvertime/Views/Home/Index.cshtml
ClientOvertime/Views/Shared/_LayoutDashboard.cshtml

feat: editing landing page

---

API/Repositories/OvertimeRepository.cs
API/Services/OvertimeService.cs
ClientOvertime/Views/Overtime/Create.cshtml

feat: update approval features

---

API/Controllers/OvertimeController.cs
ClientOvertime/Contracts/IOvertimeRepository.cs
ClientOvertime/Controllers/OvertimeController.cs
ClientOvertime/Repositories/OvertimeRepository.cs
ClientOvertime/Views/Overtime/Detail.cshtml

feat: update approval from manager

---

API/Repositories/OvertimeRepository.cs
API/Services/OvertimeService.cs

feat: update view model Manager and Update

---

API/Repositories/OvertimeRepository.cs
ClientOvertime/Views/Employee/Create.cshtml
ClientOvertime/Views/Employee/Index.cshtml
ClientOvertime/Views/Overtime/GetByManager.cshtml
ClientOvertime/Views/Overtime/Index.cshtml
ClientOvertime/Views/Payslip/Index.cshtml
ClientOvertime/Views/Shared/_LayoutDashboard.cshtml
ClientOvertime/wwwroot/js/site.js

feat: update user login

---

API/Controllers/PayslipController.cs
API/DTOs/Payslips/PayslipDtoGetMaster.cs
API/Repositories/OvertimeRepository.cs
API/Services/OvertimeService.cs
API/Services/PayslipService.cs

feat: adding view Payslip with overtime

---

API/DTOs/Payslips/PayslipDtoGetMaster.cs
API/Services/PayslipService.cs
ClientOvertime/Repositories/PayslipRepository.cs
ClientOvertime/ViewModels/Payslips/PayslipVMGet.cs
ClientOvertime/Views/Overtime/Create.cshtml
ClientOvertime/Views/Overtime/Detail.cshtml
ClientOvertime/Views/Overtime/GetByManager.cshtml
ClientOvertime/Views/Overtime/Index.cshtml
ClientOvertime/Views/Payslip/Create.cshtml
ClientOvertime/Views/Payslip/Index.cshtml
ClientOvertime/Views/Shared/_LayoutDashboard.cshtml

feat: consume api payslip in client

---

API/Services/AccountService.cs
API/Utilities/Handlers/ResponseHandler.cs
ClientOvertime/ClientOvertime.csproj
ClientOvertime/Controllers/AccountController.cs
ClientOvertime/Controllers/EmployeeController.cs
ClientOvertime/Controllers/PayslipController.cs
ClientOvertime/Views/Employee/Create.cshtml
ClientOvertime/Views/Shared/_LayoutDashboard.cshtml
ClientOvertime/Views/Shared/_LayoutLogin.cshtml

feat: add toastr login

---

ClientOvertime/Views/Employee/Create.cshtml

feat: edit required manager

---

API/Services/PayslipService.cs

feat: update payslip feature

---

API/Repositories/OvertimeRepository.cs
API/Services/PayslipService.cs
ClientOvertime/Contracts/IPayslipRepository.cs
ClientOvertime/Controllers/PayslipController.cs
ClientOvertime/Repositories/PayslipRepository.cs
ClientOvertime/Views/Overtime/Detail.cshtml
ClientOvertime/Views/Overtime/Index.cshtml
ClientOvertime/Views/Payslip/Index.cshtml

feat: Update Format Detail and Payslip

---

API/Controllers/PayslipController.cs
API/DTOs/Payslips/PayslipDtoUpdate.cs
API/Services/PayslipService.cs
ClientOvertime/Contracts/IPayslipRepository.cs
ClientOvertime/Controllers/AccountController.cs
ClientOvertime/Controllers/EmployeeController.cs
ClientOvertime/Controllers/OvertimeController.cs
ClientOvertime/Repositories/PayslipRepository.cs
ClientOvertime/ViewModels/Payslips/PayslipVMGet.cs
ClientOvertime/Views/Account/ChangePassword.cshtml
ClientOvertime/Views/Account/Login.cshtml
ClientOvertime/Views/Shared/_LayoutDashboard.cshtml

feat: update payslip fix

---

API/Controllers/PayslipController.cs
API/Services/PayslipService.cs
ClientOvertime/Contracts/IPayslipRepository.cs
ClientOvertime/Controllers/DashboardController.cs
ClientOvertime/Repositories/PayslipRepository.cs
ClientOvertime/Views/Account/ChangePassword.cshtml
ClientOvertime/Views/Account/ForgotPassword.cshtml
ClientOvertime/Views/Account/Login.cshtml
ClientOvertime/Views/Dashboard/Index.cshtml
ClientOvertime/Views/Employee/Index.cshtml
ClientOvertime/Views/Overtime/GetByManager.cshtml
ClientOvertime/Views/Overtime/Index.cshtml
ClientOvertime/Views/Payslip/Index.cshtml
ClientOvertime/Views/Shared/_LayoutDashboard.cshtml
ClientOvertime/Views/Shared/_LayoutLogin.cshtml

feat: update dashboard
